apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
    tier: frontend
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: {{ .values.services.port }}
    targetPort: {{ .values.services.targetPort }}
